accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aargus"]
  - name: bob
    coins: ["5000000000000aargus"]
validator:
  name: alice
  staked: "100000000000000000000aargus"
faucet:
  name: bob
  coins: ["10aargus"]
build:
  binary: "argusd"
init:
  home: "$HOME/.argusd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "argusd_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "aargus"
    mint:
      params:
        mint_denom: "aargus"
    crisis:
      constant_fee:
        denom: "aargus"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aargus"
    evm:
      params:
        evm_denom: "aargus"
